language: java
sudo: false

jdk:
  - oraclejdk8

install:
  - mvn package -Dmaven.javadoc.skip=true

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar/cache

notifications:
  email:
    - marcos.hgb@gmail.com